"""empty message

Revision ID: 12a6f8f3cc62
Revises: b6beb6840eea
Create Date: 2024-07-30 10:36:02.461172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12a6f8f3cc62'
down_revision: Union[str, None] = 'b6beb6840eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('board_json', sa.JSON(), nullable=False))
    op.drop_column('rooms', 'board_JSON')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('board_JSON', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'board_json')
    # ### end Alembic commands ###
