"""empty message

Revision ID: b6beb6840eea
Revises: ab2d909f5691
Create Date: 2024-07-23 15:48:15.541635

"""

import enum
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6beb6840eea"
down_revision: Union[str, None] = "ab2d909f5691"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("player_id", sa.Uuid(), nullable=False, primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("player_id"),
    )
    op.create_table(
        "rooms",
        sa.Column("room_id", sa.Uuid(), nullable=False, primary_key=True),
        sa.Column("first_player_id", sa.Uuid(), nullable=False),
        sa.Column("second_player_id", sa.Uuid(), nullable=True),
        sa.Column(
            "active_player_state",
            sa.Enum("FIRST", "SECOND", name="activestate"),
            nullable=False,
        ),
        sa.Column("board_JSON", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["first_player_id"],
            ["players.player_id"],
        ),
        sa.ForeignKeyConstraint(
            ["second_player_id"],
            ["players.player_id"],
        ),
        sa.PrimaryKeyConstraint("room_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    op.drop_table("players")
    op.execute("DROP TYPE activestate")
    # ### end Alembic commands ###
